language: c

addons:
  sonarcloud:
    organization: "autowp-github"
    token: $SONAR_TOKEN

script:
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
